#pragma once

#include <string>
#include <string_view>

namespace specforge {

enum class SampleAnnotationWorkflowRelationship;
enum class SourceCollectionSourceState;

enum class UiLanguage {
    English,
    SimplifiedChinese,
    Count,  // Non-language sentinel.
};

enum class UiTextId {
    Settings,
    Language,
    LanguagePageDescription,
    ApplicationLanguage,
    EnglishLanguageName,
    SimplifiedChineseLanguageName,
    LocalizationInProgress,
    LanguageLoadWarning,
    LanguageSaveError,
    Appearance,
    AppearancePageDescription,
    Theme,
    FollowSystemTheme,
    LightTheme,
    DarkTheme,
    AccentColor,
    AppearanceThemeUnavailable,
    UiScale,
    Reset,
    UiScaleDescription,
    UiScaleLoadWarning,
    UiScaleRejected,
    UiScaleSaveError,
    SavedSettingsValueUnreadable,
    SettingsFileWriteFailed,
    UnsupportedApplicationLanguage,
    UiScaleOutsideSupportedRange,
    ProfileEnvironmentOverrideActive,
    ProfileRecordingInProgress,
    ProfileOutputDirectoryEmpty,
    DiagnosticDetails,
    ExperimentalFrameCapture,
    ExperimentalFrameCaptureDescription,
    CaptureNextMainFrame,
    FrameCaptureWaiting,
    FrameCaptureReadbackNote,
    FrameCaptureOutputDirectory,
    UnknownSourceType,
    SourceStateUnavailable,
    SourceStateError,
    SourceStateLoaded,
    SourceStateLoadedWithDiagnostics,
    SourceStateNotPlottable,
    AnnotationRelationshipPlain,
    AnnotationRelationshipExternal,
    AnnotationRelationshipLocal,
    ApplicationWindowTitle,
    FileMenu,
    OpenFile,
    OpenFolder,
    OpenFileAsAnnotation,
    ViewMenu,
    ImmersivePlotMode,
    ShowAllPanels,
    Files,
    Navigation,
    Annotations,
    Labeling,
    SampleFilters,
    SampleSorting,
    Smoothing,
    Information,
    SpectralLines,
    Spectrum,
    SampleNameMatches,
    Ready,
    LoadFailed,
    LoadingSource,
    StateSaveRetrying,
    StateWarning,
    StateRecovered,
    Frame,
    LoadFailedDismissHint,
    PerformanceRecording,
    FinishingRecording,
    StartRecording,
    StopRecording,
    FinishingRecordingAction,
    PerformanceRecordingBadge,
    AddSourceFileDialog,
    AddSourceFolderDialog,
    SpectrumSourcesFilter,
    NumpyArraysFilter,
    CsvFilesFilter,
    FitsFilesFilter,
    AllFilesFilter,
    OpenAnnotationFileDialog,
    NumpyAnnotationArraysFilter,
    SaveLabelingAnnotationDialog,
    NumpyLabelArraysFilter,
    ChooseProfileOutputFolderDialog,
    General,
    GeneralPageDescription,
    RestorePreviousSession,
    SessionRestorationUnavailable,
    Input,
    InputPageDescription,
    MouseZoomSensitivity,
    TouchpadZoomSensitivity,
    ReverseZoomDirection,
    ViewKeyboardShortcuts,
    InputBehaviorUnavailable,
    DataAndRecovery,
    DataAndRecoveryPageDescription,
    ApplicationData,
    OpenDataFolder,
    CopyPath,
    ConfigurationPortability,
    ImportSettings,
    ExportSettings,
    ConfigurationFormatUnavailable,
    RecoveryAndReset,
    ResetWindowLayout,
    ResetApplicationSettings,
    EraseAllApplicationState,
    ResetOperationsUnavailable,
    Diagnostics,
    DiagnosticsPageDescription,
    PerformanceProfile,
    Recording,
    Finishing,
    NotRecording,
    ProfileAutoStopNote,
    CurrentProfile,
    ProfileOutputDirectory,
    ProfileDirectorySourceDefault,
    ProfileDirectorySourceSaved,
    ProfileDirectorySourceEnvironment,
    ChooseFolder,
    RestoreDefault,
    OpenOutputFolder,
    ProfileEnvironmentOverrideNotice,
    StopRecordingBeforeChangingOutput,
    ProfileOutputLoadWarning,
    ProfileOutputSaveError,
    ProfileOutputRejected,
    About,
    AboutPageDescription,
    ProductTagline,
    CopyrightNotice,
    ProprietarySoftwareNotice,
    Version,
    Distribution,
    Configuration,
    Architecture,
    Source,
    WorkingTree,
    Head,
    Graphics,
    BuildDetails,
    BuildMetadataUnavailable,
    BuildMetadataMismatch,
    Compiler,
    CMake,
    Generator,
    WindowsSdk,
    NotReported,
    ThirdPartyComponents,
    DearImGuiComponent,
    DearImGuiComponentFallback,
    ImPlotComponent,
    ImPlotComponentFallback,
    ZlibComponent,
    ZlibComponentFallback,
    ModifiedStbNotice,
    FullTermsNotice,
    DataAttributionNotice,
    PerformanceLogs,
    OpenLogFolder,
    CopyDiagnosticInformation,
    SourceMode,
    SourceRevision,
    DataDirectory,
    LogDirectory,
    DataFolderPrepareError,
    DataFolderOpenError,
    DataFolderOpened,
    DataPathCopied,
    ProfileFolderPrepareError,
    ProfileFolderOpenError,
    ProfileFolderOpened,
    ProfilePathCopied,
    LogFolderPrepareError,
    LogFolderOpenError,
    LogFolderOpened,
    DiagnosticInformationCopied,
    StartupErrorTitle,
    UnknownStartupError,
    LocalStateWarningTitle,
    LocalStateFlushIntro,
    UnsavedAreas,
    ApplicationSettingsArea,
    SourceSessionArea,
    SampleNavigationArea,
    SampleLabelingArea,
    SampleWorkflowArea,
    SpectralLineStateArea,
    LocalStateMayNotRestore,
    UseDiagnosticsToRecord,
    RecordingStartedByEnvironment,
    CouldNotStartRecording,
    RecordingPerformanceDiagnostics,
    EventsDroppedPressure,
    RecordingFailed,
    RecordingFailedWhileWriting,
    RecordingSavedAfterDuration,
    RecordingSavedAfterSize,
    RecordingSaved,
    RecordingStopped,
    EventsDropped,
    FrameCaptureReady,
    FrameCaptureDisabled,
    FrameCaptureWindowUnavailable,
    FrameCaptureRequested,
    FrameCaptureCompleted,
    FrameCaptureFailed,
    FrameCaptureDirectoryFailed,
    FrameCaptureBackendFailed,
    PanelVisibility,
    Count,  // Non-display sentinel.
};

[[nodiscard]] std::string_view UiText(UiLanguage language, UiTextId text_id) noexcept;
[[nodiscard]] std::string StableUiLabel(
    UiLanguage language,
    UiTextId text_id,
    std::string_view stable_id);
[[nodiscard]] std::string_view UiText(
    UiLanguage language,
    SourceCollectionSourceState state) noexcept;
[[nodiscard]] std::string_view UiText(
    UiLanguage language,
    SampleAnnotationWorkflowRelationship relationship) noexcept;

}  // namespace specforge
