#pragma once

#include <optional>
#include <span>
#include <string>
#include <string_view>

namespace specforge {

enum class SampleAnnotationWorkflowRelationship;
enum class SampleLabelSaveMessageKind;
enum class SourceCollectionLoadErrorKind;
enum class SourceCollectionSourceState;
enum class LocalUserStateArea;
struct LocalUserStateHealthMessage;
struct SourceCollectionLoadFailure;

enum class UiLanguage {
    English,
    SimplifiedChinese,
    Count,  // Non-language sentinel.
};

[[nodiscard]] std::string_view UiLanguageSettingValue(
    UiLanguage language) noexcept;
[[nodiscard]] std::optional<UiLanguage> ParseUiLanguageSettingValue(
    std::string_view value) noexcept;

enum class UiTextId {
    Settings,
    Language,
    LanguagePageDescription,
    ApplicationLanguage,
    EnglishLanguageName,
    SimplifiedChineseLanguageName,
    ApplicationLanguageScope,
    LanguageLoadWarning,
    LanguageSaveError,
    Appearance,
    AppearancePageDescription,
    Theme,
    FollowSystemTheme,
    LightTheme,
    DarkTheme,
    ThemeLoadWarning,
    ThemeRejected,
    ThemeSaveError,
    AccentColor,
    AppearanceAccentColorUnavailable,
    UiScale,
    Reset,
    UiScaleDescription,
    UiScaleLoadWarning,
    UiScaleRejected,
    UiScaleSaveError,
    SavedSettingsValueUnreadable,
    SettingsFileWriteFailed,
    UnsupportedApplicationLanguage,
    UnsupportedApplicationTheme,
    UiScaleOutsideSupportedRange,
    ProfileEnvironmentOverrideActive,
    ProfileRecordingInProgress,
    ProfileOutputDirectoryEmpty,
    DiagnosticDetails,
    ExperimentalFrameCapture,
    ExperimentalFrameCaptureDescription,
    CaptureNextMainFrame,
    FrameCaptureWaiting,
    FrameCaptureReadbackNote,
    FrameCaptureOutputDirectory,
    UnknownSourceType,
    FileSourceType,
    FolderSourceType,
    SourceStateUnavailable,
    SourceStateError,
    SourceStateLoaded,
    SourceStateLoadedWithDiagnostics,
    SourceStateNotPlottable,
    AnnotationRelationshipPlain,
    AnnotationRelationshipExternal,
    AnnotationRelationshipLocal,
    ApplicationWindowTitle,
    FileMenu,
    OpenFile,
    OpenFolder,
    OpenFileAsAnnotation,
    ViewMenu,
    ImmersivePlotMode,
    ShowAllPanels,
    Files,
    Navigation,
    Annotations,
    Labeling,
    SampleFilters,
    SampleSorting,
    CurveDisplay,
    Information,
    SpectralLines,
    Spectrum,
    SampleNameMatches,
    Ready,
    LoadFailed,
    BackgroundSourceLoadingFailed,
    PreparedSourceResultNotApplicable,
    PreparedSourceReuseTargetUnavailable,
    PreparedKnownSourcePlanStale,
    PreparedNavigationUnavailable,
    LoadingSource,
    StateSaveRetrying,
    StateWarning,
    StateRecovered,
    ApplicationFrameRate,
    LoadFailedDismissHint,
    PerformanceRecording,
    FinishingRecording,
    StartRecording,
    StopRecording,
    FinishingRecordingAction,
    PerformanceRecordingBadge,
    AddSourceFileDialog,
    AddSourceFolderDialog,
    SpectrumSourcesFilter,
    NumpyArraysFilter,
    CsvFilesFilter,
    FitsFilesFilter,
    AllFilesFilter,
    OpenAnnotationFileDialog,
    SampleAnnotationFilesFilter,
    SaveLabelingAnnotationDialog,
    NumpyLabelArraysFilter,
    ChooseProfileOutputFolderDialog,
    General,
    GeneralPageDescription,
    FileOpening,
    RestorePreviousSession,
    SessionRestorationUnavailable,
    Input,
    InputPageDescription,
    LiveNumericNavigation,
    LiveNumericNavigationDescription,
    InputSettingsLoadWarning,
    InputSettingsSaveError,
    MouseZoomSensitivity,
    TouchpadZoomSensitivity,
    ReverseZoomDirection,
    ViewKeyboardShortcuts,
    InputBehaviorUnavailable,
    ExternalSourceOpening,
    OpenExternalSourceAsFolder,
    OpenExternalSourceAsFolderDescription,
    IncludeExternalSubfolders,
    ExternalSourceSettingsLoadWarning,
    ExternalSourceSettingsSaveError,
    DataAndRecovery,
    DataAndRecoveryPageDescription,
    ApplicationData,
    OpenDataFolder,
    CopyPath,
    ConfigurationPortability,
    ImportSettings,
    ExportSettings,
    ConfigurationFormatUnavailable,
    RecoveryAndReset,
    ResetWindowLayout,
    ResetApplicationSettings,
    EraseAllApplicationState,
    ResetOperationsUnavailable,
    Diagnostics,
    DiagnosticsPageDescription,
    PerformanceProfile,
    Recording,
    Finishing,
    NotRecording,
    ProfileAutoStopNote,
    CurrentProfile,
    ProfileOutputDirectory,
    ProfileDirectorySourceDefault,
    ProfileDirectorySourceSaved,
    ProfileDirectorySourceEnvironment,
    ChooseFolder,
    RestoreDefault,
    OpenOutputFolder,
    ProfileEnvironmentOverrideNotice,
    StopRecordingBeforeChangingOutput,
    ProfileOutputLoadWarning,
    ProfileOutputSaveError,
    ProfileOutputRejected,
    About,
    AboutPageDescription,
    ProductTagline,
    CopyrightNotice,
    Version,
    Distribution,
    Configuration,
    Architecture,
    Source,
    WorkingTree,
    Graphics,
    BuildDetails,
    ArtifactIdentity,
    MetadataCompletedAt,
    ExecutableSha256,
    Compiler,
    CMake,
    Generator,
    WindowsSdk,
    NotReported,
    ThirdPartyComponents,
    DearImGuiComponent,
    DearImGuiComponentFallback,
    ImPlotComponent,
    ImPlotComponentFallback,
    YamlCppComponent,
    YamlCppComponentFallback,
    ZlibComponent,
    ZlibComponentFallback,
    ModifiedStbNotice,
    LegalDocuments,
    LegalDocumentsDescription,
    ThirdPartyNotices,
    DataSources,
    CopyDocument,
    Close,
    LegalDocumentUnavailable,
    PerformanceLogs,
    OpenLogFolder,
    CopyDiagnosticInformation,
    SourceMode,
    SourceRevision,
    DataDirectory,
    LogDirectory,
    DataFolderPrepareError,
    DataFolderOpenError,
    DataFolderOpened,
    DataPathCopied,
    ProfileFolderPrepareError,
    ProfileFolderOpenError,
    ProfileFolderOpened,
    ProfilePathCopied,
    LogFolderPrepareError,
    LogFolderOpenError,
    LogFolderOpened,
    DiagnosticInformationCopied,
    StartupErrorTitle,
    UnknownStartupError,
    LocalStateWarningTitle,
    LocalStateFlushIntro,
    UnsavedAreas,
    ApplicationSettingsArea,
    SourceSessionArea,
    SpectrumViewArea,
    SampleNavigationArea,
    SampleLabelingArea,
    SampleWorkflowArea,
    SpectralLineStateArea,
    LocalStateMayNotRestore,
    UseDiagnosticsToRecord,
    RecordingStartedByEnvironment,
    CouldNotStartRecording,
    RecordingPerformanceDiagnostics,
    EventsDroppedPressure,
    RecordingFailed,
    RecordingFailedWhileWriting,
    RecordingSavedAfterDuration,
    RecordingSavedAfterSize,
    RecordingSaved,
    RecordingStopped,
    EventsDropped,
    FrameCaptureReady,
    FrameCaptureDisabled,
    FrameCaptureWindowUnavailable,
    FrameCaptureRequested,
    FrameCaptureCompleted,
    FrameCaptureFailed,
    FrameCaptureDirectoryFailed,
    FrameCaptureBackendFailed,
    PanelVisibility,
    AddFile,
    AddFolder,
    OpenSourceInNewInstance,
    OpenSourceInNewInstanceFailed,
    SourceSingular,
    SourcesPlural,
    NoSourcesInSession,
    SourceColumn,
    TypeColumn,
    StateColumn,
    RemoveFromList,
    NoActiveSource,
    SourceSample,
    PreviousSampleShortcut,
    NextSampleShortcut,
    Sequence,
    SampleName,
    NoReadOnlyAnnotations,
    DisplayNameColumn,
    ValueColumn,
    AnnotationMissing,
    AnnotationOutputMissing,
    AnnotationMetadataMissing,
    AnnotationMetadataIgnored,
    NoPlottableSpectrum,
    GaussianSigma,
    MedianKernelSize,
    CurveColor,
    ColorOptionsHint,
    ResetColorToAuto,
    RawSpectrum,
    GaussianSmoothing,
    MedianSmoothing,
    CurrentSpectrum,
    Name,
    Points,
    DataPoints,
    DragOrEnterValue,
    OddKernelInputHint,
    EffectiveKernelCompact,
    NoneValue,
    UnknownValue,
    WavelengthMedium,
    ObserverCorrection,
    RadialVelocity,
    RadialVelocitySource,
    Redshift,
    RedshiftWarning,
    TargetRedshift,
    TargetRedshiftSource,
    TargetRedshiftStatus,
    TargetRedshiftWarning,
    HeliocentricCorrection,
    TargetRestFrame,
    RestFrameCorrection,
    MetadataNotApplied,
    MetadataAvailableNotApplied,
    MetadataUnreliableNotApplied,
    MetadataLowSpeedApproximation,
    MetadataPipelineRedshift,
    MetadataZWarningNonzero,
    MetadataInvalidPipelineRedshift,
    NoSnapshot,
    DiagnosticsHeading,
    NoDiagnostics,
    DiagnosticSeverityInfo,
    DiagnosticSeverityWarning,
    DiagnosticSeverityError,
    DiagnosticSeverityUnknown,
    SampleNamesFileIgnored,
    AnnotationFileIgnored,
    AnnotationMetadataFileIgnored,
    UseAnnotationAsLabelingTask,
    AddSampleFilterSource,
    AddSampleSortSource,
    DeleteLabelingTaskQuestion,
    DeleteLabelQuestion,
    ChangeUsedLabelCodeQuestion,
    Ascending,
    Descending,
    RemoveSampleSorting,
    InternalAutosaveDraft,
    AutosavedToOutput,
    PendingSave,
    SaveFailedValue,
    OutputPathAlreadyUsed,
    CouldNotSaveLabelingOutput,
    LabelingEditLeaseUnavailable,
    LabelingEditLeaseFailed,
    LabelingEditTargetChanged,
    LabelingDeleteTargetChanged,
    LabelSaveStateInternalDraft,
    LabelSaveStateAutosaved,
    LabelSaveStatePending,
    LabelSaveStateTemporaryFailed,
    LabelSaveStateOutputFailed,
    LabelSaveStateUnknown,
    Pause,
    Delete,
    SelectLabelingTask,
    NewLabelingTask,
    TemporaryLabelingTask,
    TemporaryLabelingDraft,
    ResumeLabelingDraft,
    TemporaryDraftRecovery,
    TemporaryDraftSourceIdentity,
    TemporaryDraftTaskIdentity,
    TemporaryDraftTaskColumn,
    TemporaryDraftIdentityColumn,
    TemporaryDraftStatusColumn,
    TemporaryDraftProgressColumn,
    TemporaryDraftSaveColumn,
    TemporaryDraftActionsColumn,
    TemporaryDraftCurrent,
    TemporaryDraftRecoverable,
    TemporaryDraftConflicting,
    TemporaryDraftStale,
    TemporaryDraftDuplicateIdentity,
    RecoverTemporaryDraft,
    KeepTemporaryDraft,
    TemporaryDraftKept,
    DeleteTemporaryDraft,
    OutputAutosaveCloseBlocked,
    OutputAutosaveDeleteBlocked,
    UseAnnotationEditableMessage,
    AdoptCanonicalAsdfEditableMessage,
    EditAnnotationInPlaceWarning,
    MetadataSidecarWillBeCreated,
    ExistingLabelMetadataReused,
    UseAnnotation,
    Cancel,
    DeleteLocalTaskMessage,
    DeleteTask,
    LabelingProgress,
    CurrentLabelValue,
    ImmersiveLabelPrefix,
    ImmersivePreviousLabelPrefix,
    RememberedRow,
    Resume,
    SaveStatus,
    LocalTaskRecord,
    AutoAdvance,
    SkipLabeled,
    SaveTo,
    Labels,
    AddLabel,
    DefaultLabelName,
    Code,
    Shortcut,
    PressKey,
    ShortcutCaptureInstructions,
    ShortcutCaptureWaiting,
    CaptureLabelShortcut,
    Clear,
    ShortcutUnboundOnSave,
    ShortcutKeysOnly,
    ShortcutSelected,
    ShortcutWillMove,
    ShortcutConflict,
    NameRequired,
    CodeIntegerRequired,
    UnlabeledCodeReserved,
    CodeAlreadyUsed,
    ShortcutOneCharacter,
    LabelCodeRewriteCount,
    SavingMovesShortcut,
    SaveLabel,
    CancelEditing,
    EditLabel,
    DeleteLabel,
    DeleteLabelAndClear,
    LabelCodeAssignedCount,
    LabelCodeRewriteAll,
    ChangeCode,
    LabelAssignedCount,
    DeleteLabelChangesValues,
    DeleteLabelRemovesFilter,
    AddAnnotationSampleFilter,
    NoAvailableAnnotations,
    ResetSampleFilters,
    VisibleSamples,
    CurrentSampleOutsideFilters,
    FilterSourceNotLoaded,
    FilterSourceNotFilterable,
    FilterSampleCountChanged,
    NoSampleFilters,
    RemoveSampleFilter,
    AddAnnotationSampleSorting,
    ResetSorting,
    SourceOrder,
    SampleNameSortSource,
    NoComparableSortSources,
    UnlabeledValue,
    PublicSpectralLineCatalog,
    CurrentSnapshotHasNoWavelengthAxis,
    UnknownWavelengthFrameWarning,
    Catalog,
    CatalogLoadFailed,
    NoPublicCatalogMarkers,
    SpectralLineCacheReadFailed,
    SpectralLineCacheInvalid,
    SpectralLineCacheUnsupported,
    SpectralLinePersistenceRetrying,
    SpectralLinePersistenceRecovered,
    Search,
    SpectralLineSearchHint,
    Duplicate,
    DuplicateAsUserView,
    Rename,
    RenameGroupingView,
    DeleteGroupingView,
    DeleteGroupingViewQuestion,
    CatalogMarkersRemainAfterViewDeletion,
    NoCatalogGroupingView,
    NewGroupingView,
    NewUserGroupingView,
    CatalogGroupingView,
    DefaultGroupingViewPrefix,
    CopySuffix,
    AddGroup,
    PlotVisibleCatalogMarkerCount,
    NoGroupsInView,
    SearchFilteredGroupVisibility,
    NoResolvedMarkersInGroup,
    ToggleGroupMarkerVisibility,
    SharedMarkerReference,
    DragDropCopy,
    DragDropMoveOrCopy,
    DropBetweenGroupsToReorder,
    DisbandGroup,
    ShowOnPlot,
    Unresolved,
    UnresolvedMarkerNotPlotted,
    CopyToGroup,
    NoOtherGroups,
    RemoveFromThisGroup,
    RenameGroup,
    UnassignedGroup,
    DefaultGroupPrefix,
    ViewportUnlockedTooltip,
    ViewportLockedTooltip,
    Count,  // Non-display sentinel.
};

[[nodiscard]] std::string_view UiText(UiLanguage language, UiTextId text_id) noexcept;
[[nodiscard]] std::string StableUiLabel(
    UiLanguage language,
    UiTextId text_id,
    std::string_view stable_id);
[[nodiscard]] std::string_view SourceTypeDisplayText(
    UiLanguage language,
    std::string_view source_type) noexcept;
[[nodiscard]] std::string_view UiText(
    UiLanguage language,
    SourceCollectionLoadErrorKind error_kind) noexcept;
[[nodiscard]] std::string FormatSourceCollectionLoadFailures(
    UiLanguage language,
    std::span<const SourceCollectionLoadFailure> failures);
[[nodiscard]] std::string_view UiText(
    UiLanguage language,
    SourceCollectionSourceState state) noexcept;
[[nodiscard]] std::string_view UiText(
    UiLanguage language,
    SampleAnnotationWorkflowRelationship relationship) noexcept;
[[nodiscard]] std::string_view UiText(
    UiLanguage language,
    SampleLabelSaveMessageKind message_kind) noexcept;
// Maps the stable numeric value of SampleLabelingOperationResult::Issue to
// the single localized message source. The controller enum is intentionally
// kept out of this low-level text header to avoid a UI dependency cycle.
[[nodiscard]] UiTextId LabelingIssueTextId(int issue_value) noexcept;
[[nodiscard]] std::string_view UiText(
    UiLanguage language,
    LocalUserStateArea area) noexcept;
[[nodiscard]] std::string FormatLocalUserStateHealthMessage(
    UiLanguage language,
    const LocalUserStateHealthMessage& message);

}  // namespace specforge
